/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Comparator;
import java.util.List;

public class WorldCupMain {

    public static void main(String[] args) throws IOException {
        List<WorldCupMatch> data = new WorldCupCsvParser().parse(new InputStreamReader(WorldCupMain.class.getResourceAsStream("/input_alle_spiele_nurVorrund.csv")));

        System.out.println("All matches:");
        data.forEach(System.out::println);

        System.out.println("All matches ordered by time:");
        data.stream().sorted(Comparator.comparing(WorldCupMatch::startTS)).forEach(System.out::println);

    }
}
